# Use root/example user/password credentials
version: "3.1"

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    # image: php:7.4-apache
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html/
    # networks:
    #   - my-web
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
    volumes:
      - my-mysql:/var/lib/mysql
    ports:
      - 3306:3306
    # networks:
    #   - my-web

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  my-mysql:
